### ISSUE TITLE
Discuss adopting ktlint

### ISSUE THREAD

**Issue by goncalossilva** [Doist/java-kotlin-code-styles#5]
In the latest update to the code style, a section of the discussion was about formatting being the machine's job and ideally not something that needs to ever be discussed, nor manually tweaked by the developer.

For Kotlin, Klint seems *excellent*: https://github.com/pinterest/ktlint/blob/master/README.md

It seems to be exactly what we need, complements the built-in formatter, is well maintained, widely used, and integrates with everything one could ask for: IntelliJ, Gradle, CI, git hooks, etc.

I think we should adopt this for all Kotlin projects and be done with bikeshedding. 😊

**Comment by rastislavvasko** [comment]
Agreed! I was going to add it [last week](https://twist.com/a/1585/ch/1290/t/1501357/c/57206802). 😃 But still exploring which plugin to use, where to add it in tooling and the default settings (i.e. there's different import ordering between AS and ktlint).

**Comment by goncalossilva** [comment]
Sounds great! It feels like this could solve a lot of the nuance around manual formatting.

> 

This feels unexpected, as one of their goals is to extend (vs replace) the official code style. :confused: 

![Screenshot-20200427122756](https://user-images.githubusercontent.com/102931/80367374-e22dcd80-8882-11ea-8a1e-69ac6c59d50a.png)
)

**Comment by rastislavvasko** [comment]
Fixed in https://github.com/Doist/java-kotlin-code-styles/pull/6 + https://github.com/Doist/Todoist-Android/pull/897. 😊
